config/routes.rb
Server::Application.routes.draw do

  resources :coffee_drinkers

  get "log/increment", to: 'coffee_drinkers#increment'
  get "log/create_new", to: 'coffee_drinkers#create_new'
  get "log/reset", to: 'coffee_drinkers#reset'

  get "log/week_cups", to: 'coffee_drinkers#week_cups'
  get "log/cup_count", to: 'coffee_drinkers#cup_count'
  get "log/new_cups", to: 'coffee_drinkers#new_cups'

  root :to => 'coffee_drinkers#index'

resources :cup_of_coffees

  

end

app/models/coffee_drinker.rb
include CoffeeDrinkersHelper

class CoffeeDrinker < ActiveRecord::Base
  has_many :cup_of_coffees

  def week_cups_grouped_by_day
      return get_cup_data_series(week_start())
  end

  def get_cup_data_series (since_date)

    date_range = since_date.to_date..Date.today

    cups = CupOfCoffee.where("coffee_drinker_id = ? AND created_at >= ?", self.id, since_date.beginning_of_day)
    cups = cups.group_by {|cup| cup.created_at.to_date } # Gets a hashmap, date => cups

    data = []
    date_range.each do |day|
      cup_count = cups[day.to_date] == nil ? 0 : cups[day.to_date].length
      data << [day.to_date, cup_count]
    end

    return data;
  end

  def as_json (options={})
    # add whatever fields you need here
    { :name => self.name, :id => self.id, :data => self.week_cups_grouped_by_day }
  end

end

app/controllers/coffee_drinkers_controller.rb
#encoding: utf-8
include CoffeeDrinkersHelper

class CoffeeDrinkersController < ApplicationController

	def index
    gon.pusher_key = Pusher.key
		@hs_list = highscore_list(week_start())
	end

  def show
  	puts params[:id]
  	@drinker = CoffeeDrinker.find_by_card_uid(params[:id])
  	@group = @drinker.cup_of_coffees.group('date(created_at)').count
  	@group = @drinker.cup_of_coffees.group_by(&:created_at).map {|k,v| [k, v.length]}.sort
  	@drinklog = @drinker.cup_of_coffees.order('created_at DESC').group_by {|video| video.created_at.to_date }

  end


  
	def increment
		uid = params[:uid]
		
		if uid == ''
			return render :status=>400, :text=> "$=0"
		end
		
		@drinker = CoffeeDrinker.where(card_uid: uid).first
		
		if @drinker.nil?
			
			return render :inline => "$=2"
		end
		

		latest_cup = @drinker.cup_of_coffees.order('created_at DESC').first
		
		if params[:days] # DEBUG HELPER
			newCup = CupOfCoffee.new
			newCup.created_at = DateTime.now - params[:days].to_i
			@drinker.cup_of_coffees << newCup
			puts "OOOOO Added filthy debug coffee for #{@drinker.id} #{newCup.created_at}"

    elsif latest_cup.nil? || latest_cup.created_at < Time.now-50.seconds
      @drinker.cup_of_coffees << CupOfCoffee.new

      selector = "created_at > '%s 04:30:00'" % Time.now.to_date.to_formatted_s(:db)

      cups_today = @drinker.cup_of_coffees.where(selector).count

      Pusher['new_data'].trigger('refresh', {
          drinker: @drinker.name,
          cups: cups_today
      })

			return render :status=>200, :text=> "$=1Hej %s,|%s koppar idag! " % [@drinker.name, cups_today]
		else
			return render :status=>400, :text=> "$=1Hej %s!|Redan loggad! " % [@drinker.name]
		end
		
		
  
  end
  
	def create_new
	
			uid = params[:uid]
			name = params[:n]
			
			@drinker = CoffeeDrinker.where(card_uid: uid).first

			if @drinker.nil? && uid != '' && name != ''
				
				@drinker = CoffeeDrinker.new
				@drinker.card_uid = uid
				@drinker.name = name
				@drinker.save
				return render :status=>200, :text=> "$=1"
			else
				return render :status=>400, :text=> "$=0"
			end
	end
	
	def reset
		CoffeeDrinker.delete_all
		return render :text => "tog bort allt :s"
	end
	
	def week_cups
  	drinkers = CoffeeDrinker.all

  	@hs_list = highscore_list(week_start())
  	highscoreHtml = render_to_string(partial: "highscore", layout: false)

  	render json: {:title => "Coffee Week", :subtitle => "Hot boiling joy since #{week_start.to_date}", :seriesData => drinkers, :highscoreHtml => highscoreHtml}
  end

  def cup_count
  	filter_week = params[:week]
  	@drinkers = CoffeeDrinker.all
  	data = []

  	@drinkers.each do |drinker|
  		datapoint = {
  			name: drinker.name,
  			id: drinker.id,
  			y: filter_week == "true" ? drinker.cup_of_coffees.since(drinker.id, week_start).length.to_f : drinker.cup_of_coffees.length.to_f
  		}

  		data << datapoint
  	end

  	max = data.max_by do |el|
  		el[:y]
  	end

  	index_of_max = data.index(max)
  	data[index_of_max] = {
  		name: max[:name],
  		id: max[:id],
  		y: max[:y],
  		sliced: true,
  		selected: true
  	}
  	@hs_list = filter_week == "true" ? highscore_list(week_start()) : highscore_list
  	highscoreHtml = render_to_string(partial: "highscore", layout: false)

  	title = filter_week == "true" ? "Week Totals"
  																: "Highscore"

  	subtitle = filter_week == "true" ? "Individual share of total hot boiling joy since #{week_start.to_date}"
  																		: "Individual share of total hot boiling joy since FOREVER"
  	returnData = {:title => title, :subtitle => subtitle, :seriesData => data, :highscoreHtml => highscoreHtml}
  	render json: returnData
  end

  # Unused?
  def new_cups
  	timeInt = params[:since] || Time.now
  	sinceTime = Time.at(timeInt.to_i)
  	new_cups = {}
  	CupOfCoffee.where('created_at >= ?', sinceTime).group_by { |cup| cup.coffee_drinker_id }.each do |id, cups|
  		new_cups[id] = cups.length
  	end
  	
  	highscoreHtml = ""
  	if new_cups.length > 0
  		@hs_list = highscore_list()
  		highscoreHtml = render_to_string(partial: "highscore", layout: false)
  	end
  	render json: {newCups: new_cups, highscoreHtml: highscoreHtml}
  end

  def highscore_html
  end


end

app/helpers/coffee_drinkers_helper.rb
module CoffeeDrinkersHelper

	def days_since_week_start
		locale_offset  = 1 # Monday is day 1, haven't found a convenient way of setting locale locally. Probably have to conf it system wide
    	days_since_start_of_week = (Date.today.wday - locale_offset) % 7

    	return days_since_start_of_week
    end

    def week_start
    	return days_since_week_start().days.ago
    end

    def drinkers_with_weeks_cups()
    	drinkers = CoffeeDrinker.all
    	drinkers.each do |drinker|
  			drinker.cup_of_coffees = drinker.cup_of_coffees.select do |cup|
  				cup.created_at >= week_start()
  			end
  			drinker.cup_of_coffees = drinker.cup_of_coffees.where('created_at >= ?', week_start())
  		end
	  	return drinkers
    end

    def highscore_list(since=nil)
    	hs = []
    	CoffeeDrinker.all.each do |drinker|
  			drinker = {
  				name: drinker.name,
  				cups: since.nil? ? drinker.cup_of_coffees.length : drinker.cup_of_coffees.since(drinker.id, since).length,
  				id: drinker.id,
  				card_uid: drinker.card_uid
  			}
  			
  			hs << OpenStruct.new(drinker)
  		end

  		return hs.sort_by { |d| d.cups }.reverse

    end
end

app/views/coffee_drinkers/_highscore.html.erb
<table id="highscore">
	<thead>
		<tr class="highscore-header"><th>#</th> <th>Drönare</th> <th>Koppar</th> </tr>
	</thead>
	<tfoot>
	</tfoot>
	<tbody>
		<% counter = 0 %>
		<% @hs_list.each do |drinker| %>
			<tr class="drinker" data-id="<%= drinker.id %>">
				<td class="hs-rank"> <%= counter += 1 %> </td>
				<td class="hs-name"><%= link_to drinker.name, "/coffee_drinkers/#{drinker.card_uid}"%></td>
				<td class="hs-cups"><%= drinker.cups %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/coffee_drinkers/decrement.html.erb
<h1>Test#decrement</h1>
<p>Find me in app/views/test/decrement.html.erb</p>

app/views/coffee_drinkers/index.html.erb
<div class="view-switch">
    <button class="view-btn btn btn-small show-area">Vecka dag för dag</label>
    <button class="view-btn btn btn-small show-pie">Veckototal</label>
    <button class="view-btn btn btn-small show-highscore">Highscore</label>
</div>

<%= audio_tag asset_path('pling.mp3'), id: 'increment-audio', type: 'audio/mp3' %>
<div id="container"></div>

<div id="highscore-container">
    <%= render "highscore" %>
</div>

<script type="text/javascript">

$(function () {
    $('.drinkers-cups').hide();
    coffee.drinkers.init();
});
</script>

app/views/coffee_drinkers/show.html.erb
<%= link_to '<- Top of the pops', coffee_drinkers_url %>

<h1>Kaffedrickare <%= @drinker.name %>  (#<%= @drinker.card_uid %>)</h1>
<% @drinklog.each do |day, cups| %>
  <%= day.strftime("%F") %>
  <ul>
  <% cups.each_with_index do |cup, index| %>
	<li>
		Cup #<%= index %> (id: <%= cup.id %>),
		<%= cup.created_at %>
		<%= link_to 'Delete', cup, method: :delete %>
	</li>
  <% end %>
 </ul>
<% end %>